# Generated by Django 6.0 on 2025-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anxietytrigger',
            name='behaviour',
            field=models.TextField(blank=True, help_text='What did you do or avoid?'),
        ),
        migrations.AddField(
            model_name='anxietytrigger',
            name='outcome',
            field=models.TextField(blank=True, help_text='What was the result or consequence?'),
        ),
    ]
