# Generated by Django 6.0 on 2026-01-29 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0003_journalentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='resilia.anxietytrigger'),
        ),
    ]
