# Generated by Django 6.0 on 2026-01-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0004_journalentry_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('theme', models.CharField(choices=[('journal', 'Free Journal'), ('reflection', 'Trigger Reflection')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
