# Generated by Django 6.0 on 2026-02-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0007_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('organisation_type', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyprompt',
            name='theme',
            field=models.CharField(choices=[('journal', 'Free Journal'), ('reflection', 'Trigger Reflection')], default='journal', max_length=20),
        ),
        migrations.AlterModelTable(
            name='anxietytrigger',
            table='noorforher_anxietytrigger',
        ),
        migrations.AlterModelTable(
            name='dailyprompt',
            table='noorforher_dailyprompt',
        ),
        migrations.AlterModelTable(
            name='journalentry',
            table='noorforher_journalentry',
        ),
    ]
