# Generated by Django 6.0 on 2026-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0008_organisationlead_alter_dailyprompt_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisationlead',
            name='organisation_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisationlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('demo', 'Demo Scheduled'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
