# Generated by Django 6.0 on 2026-02-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0009_organisationlead_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBTExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('mood_level', models.CharField(choices=[('low', 'Low anxiety'), ('moderate', 'Moderate anxiety'), ('high', 'High anxiety'), ('overwhelmed', 'Overwhelmed')], max_length=20)),
            ],
            options={
                'db_table': 'noorforher_cbtexercise',
            },
        ),
    ]
