# Generated by Django 6.0 on 2026-02-25 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0010_cbtexercise'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cbtexercise',
            table='resilia_cbtexercise',
        ),
    ]
