# Generated by Django 6.0.3 on 2026-03-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0011_alter_cbtexercise_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationlead',
            name='organisation_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
