# Generated by Django 6.0.3 on 2026-03-13 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0012_alter_organisationlead_organisation_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='organisationlead',
            name='country',
            field=models.CharField(blank=True, default='UK', max_length=100),
        ),
        migrations.AlterField(
            model_name='organisationlead',
            name='organisation_size',
            field=models.CharField(blank=True, default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
