# Generated by Django 6.0.3 on 2026-03-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0013_organisationlead_city_organisationlead_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlead',
            name='phase',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
