# Generated by Django 6.0.3 on 2026-03-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0014_organisationlead_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='free_access',
            field=models.BooleanField(default=False),
        ),
    ]
