# Generated by Django 6.0.3 on 2026-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0015_accesscode_subscription_free_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationlead',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
