# Generated by Django 6.0.3 on 2026-04-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0018_subscription_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='has_used_trial',
            field=models.BooleanField(default=False),
        ),
    ]
