# Generated by Django 6.0.3 on 2026-04-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0019_subscription_has_used_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='free_access',
            field=models.BooleanField(default=False),
        ),
    ]
