# Generated by Django 6.0.3 on 2026-04-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0020_alter_subscription_free_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
