# Generated by Django 6.0.3 on 2026-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0022_exercisecompletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexercise',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
