# Generated by Django 6.0.3 on 2026-04-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0023_alter_cbtexercise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexercise',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AddField(
            model_name='cbtexercise',
            name='duration',
            field=models.IntegerField(default=2),
        ),
    ]
