# Generated by Django 6.0.3 on 2026-04-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0024_cbtexercise_category_cbtexercise_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbtexercise',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
