# Generated by Django 6.0.3 on 2026-04-23 12:26

import resilia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0026_affiliate_subscription_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliate',
            name='code',
            field=models.CharField(default=resilia.models.generate_code, max_length=50, unique=True),
        ),
    ]
