# Generated by Django 6.0.3 on 2026-04-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0028_remove_affiliate_name_affiliate_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
