# Generated by Django 6.0.3 on 2026-06-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0032_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
