# Generated by Django 6.0 on 2026-01-30 15:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noorforher', '0005_dailyprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
